### ISSUE TITLE
What versions of .NET are supported?

### ISSUE THREAD

**Issue by gsvgit** [panthernet/GraphX#11]
What versions of .NET are supported? We have a problem with Zoom control in .NET 4.0 application.

Thanks.

**Comment by panthernet** [comment]
Hi, GraphX supports .NET Framework version 4.0.3 and higher. What kind of issue you have with ZoomControl?

**Comment by gsvgit** [comment]
Seems that we have problems because we build all projects in .NET 4.0, not in 4.0.3 for UI projects.  For 4.0.3 everything works fine. Thank you.

Error message : The tag 'ZoomControl' does not exist in XML namespace 'clr-namespace:GraphX.Controls;assembly=GraphX.WPF.Controls'

**Comment by panthernet** [comment]
I'm glad you've managed to solve this issue. If you'll have any questions please feel free to ask.
