### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by MannusEtten** [panthernet/GraphX#122]
![image](https://user-images.githubusercontent.com/47241453/132254090-9c0a42c3-cf8b-4320-8039-13b9a6036efc.png)

how can i redraw the graph so it will be good again?

**Comment by bleibold** [comment]
You probably need to provide more context...

Why do you need to redraw?
Does the whole graph need revalidated?
What changed that requires the graph to be redrawn?

**Comment by MannusEtten** [comment]
i fill the graph with new vertices so i have to redraw it completely because all the vertex are different. I do have a list with items. When i select an item it will get the vertices from the database. Every item does have a new and other set of vertices. So that is why I need to redraw the whole graph again.
