### ISSUE TITLE
Feature - snap to grid, snap to neighbor

### ISSUE THREAD

**Issue by jorgensigvardsson** [panthernet/GraphX#13]
This is very useful when manually rearranging nodes. Snap to neighbor is a simple issue, maybe allow the function to have some options such as
- Snap to vertical/horizontal centers
- Snap to top/bottom/left/right border alignment

Snap to grid is somewhat trickier, as the grid can be relative to the screen (pixels), or relative to the control's zoom factor. Maybe both options should be considered.

Is it worthwhile pursuing? I think it'd be a nice feature for OCD-disabled people like myself.. :laughing:

**Comment by panthernet** [comment]
So you want to implement smth like virtual grid that can be turned on/off and vertices can be aligned to that grid on demand? Am i correct?

**Comment by jorgensigvardsson** [comment]
Yeah, exactly! If you have little time, I can give it a stab.

**Comment by panthernet** [comment]
This can be a handy feature, you can try to implement it :) I think it's all about DragBehaviour class as it is responsible for vertex movement, but not sure how to handle grid visualization if you'll want to implement it.

**Comment by jorgensigvardsson** [comment]
I'll have a look at the drag behaviour class this evening (this rare unbooked evening!) :laughing:

I'll probably do it in three steps:
1) Get snapping in place (both against virtual grid and neighbors)
2) Get drawing of snap grid working
3) Get drawing of "virtual snap lines" against neighbors working

Of course, these changes will have an effect on the API, but I think they'll add to it, rather than change and/or delete from it. 

About snap grid: I will not let the user set a size for the grid. I will make it use multiples of some constant (say 5 pixels). That way, I can adapt the grid dynamically depending on the zoom factor. Since GraphX is not an "exact drawing program", I think a dynamic grid should suffice the needs of most users that only want to organize nodes on the screen. What do you think?

**Comment by panthernet** [comment]
Yeah, i think there will be minimal breaking changes needed for an API. Overall this thing looks good and will represent nice feature for GraphX :) Dynamic grid should be the right solution as it seems casual for usage and pro to develope at the same time. If you need any help/questions please let me know, currently i'm quite busy with my main work but i'll try to help in any way.

**Comment by birbilis** [comment]
Sometimes instead of drawing grid lines they draw dots in the background where grid lines would intersect

**Comment by panthernet** [comment]
Thanks for the tip! This could be an option.

**Comment by birbilis** [comment]
in fact, such dots could even be custom objects at an extreme (more optimal though is maybe to have the API accept an object that knows to size and draw the "dot" - then could even have a "drawer" implementation that accepts XAML or a UIElement, draws it into a buffer and just paints that image [with transparency] every time it as asked to)

**Comment by panthernet** [comment]
Implemented in a basic variation
