### ISSUE TITLE
GraphX.WPF.Controls build target set to x86 instead of AnyCPU

### ISSUE THREAD

**Issue by birbilis** [panthernet/GraphX#20]
How come GraphX.WPF.Controls build target (at Project Properties, Build tab) is set to x86 instead of AnyCPU? Example projects that add it as a reference are set as AnyCPU themselves and warn this may cause runtime issues (e.g. if you run them on x64 I don't know if they will talk to the x86 DLL via WoW64 [http://en.wikipedia.org/wiki/WoW64] which would make them run slower since they'd use marshalling probably or other context switching mechanism at each call into GraphX DLL)

**Comment by panthernet** [comment]
Yeah it can be so in Debug mode, but in Release (which is used to deliver precompiled DLLs) it is set to AnyCPU.  x86 supports edit and continue in vs, so i use it in dev process.
