### ISSUE TITLE
QuickGraph on NuGet has no PCL version?

### ISSUE THREAD

**Issue by birbilis** [panthernet/GraphX#24]
When I clone GraphX repository locally (either from my own birbilis/GraphX fork or from the main panthernet/GraphX repo) and try to build I see that NuGet packages are missing and via Manage NuGet Packages (right clicking on various projects) I select to rebuild them (it fetches them from the network). 

However when I compile I get error at "GraphX.PCL.Logic", that seems to be related to "QuickGraph" not having a PCL version on NuGet

Warning 2   Some NuGet packages were installed using a target framework different from the current target framework and may need to be reinstalled. Visit http://docs.nuget.org/docs/workflows/reinstalling-packages for more information.  Packages affected: QuickGraph       0   0   GraphX.PCL.Logic

I also see the strange error

Error   1   The project 'Examples' is unsupported       0   0   

with no more info

**Comment by panthernet** [comment]
Yes where there some problems with Quickgraph NuGet. Though it should support PCL libraries.

**Comment by birbilis** [comment]
I see at http://quickgraph.codeplex.com/
QuickGraph 3.6. Portable Class Library support. 
so maybe NuGet package is older?

maybe you could submit to NuGet separate QuickGraph that includes PCL? Or if the QuickGraph project still has a maintainer, maybe they could be consulted by filing an issue on that project's site? Wonder if that NuGet package you use was uploaded to NuGet by them or some third party

btw, came across this one that may be interesting:
https://github.com/orellabac/TopologicalSort

**Comment by panthernet** [comment]
Yeah there are definetly some problems with Quickgraph on NuGet. It supports PCL but seems to have wrong package format and can't be recognized by METRO apps properly. I'll try to create correct package and upload it to NuGet as I can't get in contact with the original author which seems to be absent on CodePlex for a long time.

Thanks for spotting this. Though in GraphX it is currently solvable by two full solution build :) (cranky but it works). I'll also clean up solution a bit as it seems I've missed some old unused files in the repo.

**Comment by panthernet** [comment]
QuickGraphPCL has been deployed and GraphX Build has been successfully fixed! :)

QuickGraphPCL now contains correct internal structure and can be linked to almost any project except Silverlight4. Can't see much point in solving troubles to make it available for SL4 as there is SL5 available and SL tech isn't developed anymore.

Btw, did you know that Google will abandon SL support (along with other NETSCAPE API using stuff) in future Chrome versions somewhere around this fall or end of the summer?

**Comment by birbilis** [comment]
For SL4 you need separate PCL dll and choose at its options the SL4 profile instead of SL5 from what I remember. That's why I was saying recently that they should have named those PCL profiles, say PCL1, PCL2 (like api generations)

**Comment by birbilis** [comment]
For Chrome's hiding of NPAPI plugins see workaround at https://zoomicon.wordpress.com/2015/05/26/fix-enable-silverlight-other-npapi-plugins-at-chrome-web-browser/

Google are acting very bad in my opinion and recently they've announced they'll stop autoplaying flash ads even though they were advertising flash's stop of using NPAPI in Chrome and its using of their  proprietary Pepper API instead 

They should have seen how well firefox handles npapi plugins instead, UI-wise too

The we are not evil of Google is just a big lie btw, EU is already after their practices with Android. Hope time will come to investigate their practices with Chrome (where they are adding Android extensions but are trying to take out NPAPI plugins since those form competitive ecosystems to them)

**Comment by panthernet** [comment]
> For Chrome's hiding of NPAPI plugins see workaround at

Yeah, i know that workaround but it seems it will be cut off in future versions if i understood it correctly. Agressive market forces to make agressive decisions though it would be better if it was all about new tech/performance & flexibility as they've described these changes.

**Comment by birbilis** [comment]
Luckily Mozilla will keep supporting Netscape Plugin API, so does IE with its ActiveX (in fact could make a DLL that is both NPAPI plugin and ActiveX control easily). On Win10 MS are promoting Edge (codename spartan) that has no powerful  extension system (yet), but IE still exists there.

They have a bit of chrome extension support in edge but only for html/js based ones

**Comment by birbilis** [comment]
Btw, SL4 is a platform not needed to be supported unless someone targets Moonlight on Linux, which is obsolete though since you can use Microsoft's SL5 on Linux via PipeLight plugin (uses Wine). 

On WinXP too you can use SL5 and in fact Silverlight is the only way to deliver XAML based apps to WinXP (Greek schools have WinXP and so do many users still in Greece which was one of the reasons I chose Silverlight to deploy ClipFlair, apart from the ease of app deployment and update and the embedded crossplatform codecs and fonts it has that is)

**Comment by panthernet** [comment]
I see :) WinXP still lives :)

**Comment by birbilis** [comment]
btw, just came across an interesting article that explains PCL and in fact it does contain Profiles, they're just not "advertised". The article also speaks of changes to NuGet now that more platforms are being added and has lots of internals info: http://oren.codes/2015/06/16/demystifying-pcls-net-core-dnx-and-uwp-redux

**Comment by birbilis** [comment]
btw, this is also showing the PCL profiles (the article above explains the concept and how MS is moving past it now): Portable Class Library (PCL) profiles as of VS2013 Update 4 - http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY/preview

**Comment by sebandraos** [comment]
Are the corrections to QuickGraph to make QuickGraphPCL available from the QG CodePlex or are they tucked away somewhere else? I'm looking to create a NETStandard version as this is due to replace PCLs soon and QuickGraph is the last of my dependencies that hasn't been updated.

**Comment by panthernet** [comment]
Hello, i've taken the latest version from CodePlex to make the PCL one. But you might also be intersted in the continuation of Quickgraph here: https://github.com/YaccConstructor/QuickGraph

Btw, PCL quickgraph should compile fine with standard .NET, doesn't it?

**Comment by sebandraos** [comment]
I did have a look at Yacc's version but they've removed the portability aspect you had added with references to F# and the like. I'm not sure it's actually a question of compilation, it's a nuget issue in that there is a new file structure needed within nuget to allow a netstandard library to reference it. I haven't tried directly referencing the binary but wanted to make sure I was testing on the version most likely to work. I'm missing a couple of other dependencies to be able to test properly but I will look at this once the others are in place.
Thanks
