### ISSUE TITLE
How to get deterministic results?

### ISSUE THREAD

**Issue by jacku-abide** [panthernet/GraphX#41]
Would be good if we could get deterministic results when it generates the layout. Is there a way to do this?

The algorithms are clearly using Random() somewhere within them. Is there a way to set the seed so we can get predictable results?

**Comment by panthernet** [comment]
Hello, this depends on the algorithm but generaly most of them uses random initial seed. For example, _LinLog_ algorithm uses _InitializeWithRandomPositions()_ method of its base class to seed initial values. You can derive from _LinLogLayoutAlgorithm_ and override mentioned method to get predictable initial seed and thus get determenistic results.

You can do that for several other algorithms as well. Hope this help.
