### ISSUE TITLE
Why field SourceConnectionPoint is internal?

### ISSUE THREAD

**Issue by freekspb** [panthernet/GraphX#42]
Class EdgeControlBase has fields:
internal Point? SourceConnectionPoint;
internal Point? TargetConnectionPoint;

Why this fields is internal? I think they will be internal protected, because 
I inherited class EdgeControl and override method PrepareEdgePath. In my class I can't set value to SourceConnectionPoint and TargetConnectionPoint. But  method UpdatePosition of EdgeLabelControl uses value of SourceConnectionPoint and TargetConnectionPoint. But i don't want override UpdatePosition.

**Comment by panthernet** [comment]
Hi, thanks for feedback. I'll check it.

**Comment by panthernet** [comment]
Sure, this is not logical so i've updated these properties to be protected internal. Haven't got a chance yet to work with derived controls so all these stuff is polished on requests like yours. Thanks!

PS: If you'll find more stuff like that just let me know

**Comment by freekspb** [comment]
Thanks!
