### ISSUE TITLE
Self-looped vertices

### ISSUE THREAD

**Issue by phamhathanh** [panthernet/GraphX#43]
Currently the self-looped vertices are indicated with a star in the corner. I think this is somewhat unclear and unintuitive. An arrow which starts and ends in the same vertex would be better IMO. It also makes it possible to display label on these kind of edge.

**Comment by panthernet** [comment]
Hi, you can define **<Path x:Name="PART_SelfLoopedEdge"** in **EdgeControl** template and set any form you like, for ex. try setting **Data="F1 M 18,42.5L 18,49L 27,57L 36,48.5L 36,42.5L 30,47.7903L 30,35.5C 30,29.701 34.701,25 40.5,25C 46.299,25 51,29.701 51,35.5C 51,41.1314 46.5668,45.7273 41,45.9883L 41,51.9926C 49.8814,51.7283 57,44.4454 57,35.5C 57,26.3873 49.6127,19 40.5,19C 31.3873,19 24,26.3873 24,35.5L 24,47.875L 18,42.5 Z "** As i remeber correctly edge label in this case should be aligned to vertex.

**Comment by phamhathanh** [comment]
Well, to be honest, I'm not familiar with WPF, so I ended up tinkering with the core logic's properties. It would be great if there are some properties that affects these behaviors too.
