### ISSUE TITLE
Large Data Plotting Issue

### ISSUE THREAD

**Issue by tuheedakram** [panthernet/GraphX#46]
If the data is large is takes quite time to load and it becomes quite slow when the graph is with images.
I want to load more than 5000 nodes. but it takes quite time to load more than 1000

**Comment by panthernet** [comment]
I think none of the WPF based and feature rich visualization engines can be performant for large amount of vertices, though you can do some tricks. 

You can try to Cache canvas into a bitmap to speed up rendering. This will make zooming and interacting with graph less efficient but you will navigate large graphs with better performance. You need the CacheMode property.

Currently the edges rendering is a huge performance hit and it will be optimized in the future versions.

**Comment by panthernet** [comment]
FastGraphX control will be implemented in future releases. It will be specifically designed to handle large amount of data sacrificing the rich templating and high level customization features in fovar of ultimate performance and low level drawing system access.
