### ISSUE TITLE
Move to C#6 features

### ISSUE THREAD

**Issue by galakt** [panthernet/GraphX#49]
I looked at source code and saw a lot of places to use latest C# 6 features. So what you say if i will make changes and submit PR?

**Comment by panthernet** [comment]
Hello, sure, you can propose enhancements as long as they don't break the .net 4.0 requirement (as of now).

**Comment by panthernet** [comment]
Now i think i'll go straight for VS2015 and C#6.0 features. I liked the additions a lot :)

**Comment by panthernet** [comment]
Submit PR if you want to, will close this issue
