### ISSUE TITLE
Consider moving documentation to GitHub

### ISSUE THREAD

**Issue by auduchinok** [panthernet/GraphX#52]
I've been looking for GraphX documentation and found [panthernet.ru](http://panthernet.ru) (current docs hosting) being down.
Why host docs in different place?

**Comment by panthernet** [comment]
Yeah, i'm thinking about it. Just can't handle the problems with hosting well, viruses are bugging me. Hope to fix it soon.

**Comment by auduchinok** [comment]
Any news on this one?

**Comment by panthernet** [comment]
Started the transition. Will fetch pages from DB and adopt them for GitHub wiki.

**Comment by panthernet** [comment]
Moved all the stuff from the broken site, will check for correct info due to version upgrade when i'll have some time to spare.

**Comment by jakubkrzysztofsikora** [comment]
If you need any hosting let me know I have a linux server for my own purposes, I will happily help you out (of course free of any charge) as I use your lib in my master thesis. :) https://github.com/needcash/MagisterkaFinal

Cheers!

**Comment by panthernet** [comment]
Thanks, but i have one, just have to make it work.
