### ISSUE TITLE
Edge with equal SourceConnectionPoint and TargetConnectionPoint

### ISSUE THREAD

**Issue by galakt** [panthernet/GraphX#58]
WPF:
GraphX.Controls.EdgeControlBase.PrepareEdgePath method

We can place items when SourceConnectionPoint of edge equals TargetConnectionPoint of edge.
https://github.com/panthernet/GraphX/blob/PCL/GraphX.Controls/Controls/EdgeControlBase.cs#L778
That cause a little bit odd behavior of edge.

I think i can add check equal condition and change point little.

![1](https://cloud.githubusercontent.com/assets/4105997/16839238/b634c16e-49d6-11e6-94be-133dc1bd35bc.png)
![2](https://cloud.githubusercontent.com/assets/4105997/16839239/b637b4fa-49d6-11e6-961c-5870b377b6b5.png)

**Comment by panthernet** [comment]
Hello, thanks for report.  This scenarion wasn't the expected one :)  I don't see much sense in assigning the same connetion point to surce and target. I'm in for not allowing to do so, will it be correct for your case?

**Comment by galakt** [comment]
My main goal is prevent showing alone arrow (in [0;0] point) when source and target points are equal (that can happen accidentally after manual graph generation and sometimes after dragging).
It is not cool, but now for a while i just added:

```
        if (p1 == p2)
        {
            p1.X = double.PositiveInfinity;
            p1.Y = double.PositiveInfinity;
            p2.X = double.PositiveInfinity;
            p2.Y = double.PositiveInfinity;
        }
        SourceConnectionPoint = p1;
        TargetConnectionPoint = p2;
```

**Comment by panthernet** [comment]
I've checked how it works and it looks like self looped edge. If you have an edge where source and target vertices are the same then the self looped edge indicator will be drawn in the top left corner of the vertex. On the other side the code execution should not pass to the place you'd made the fix in if it is the self looped edge we talk about.  Unless you'd changed something in original logic. Originally edge can't have equal source and target connection points.

**Comment by galakt** [comment]
I have made sample to show what i mean:
https://github.com/galakt/GraphXSample2

**Comment by panthernet** [comment]
Thanks for the sample, unfortunately i'm quite busy right now. Can't promise much but will try to spare some time on the issue.

**Comment by panthernet** [comment]
Fixed! That was an intersting case where vertices were so close together that edge were almost zero length making rotation calc return NaN value messing up the final pointer position. Also i've implemented the _EdgeControlBase::HideEdgePointerOnVertexOverlap_ property which allows you to hide edge pointer in such cases (default) or display them at the edge pos if set to false.
