### ISSUE TITLE
Odd default parameters and method comments

### ISSUE THREAD

**Issue by galakt** [panthernet/GraphX#60]
I found interesting method:
https://github.com/panthernet/GraphX/blob/PCL/GraphX.PCL.Logic/Models/GXLogicCore.cs#L350

Method provide default values, but if dont change it then exception will thrown. Also method comments say 

> (auto filled if null)

**Comment by panthernet** [comment]
Hi, seems like the method comments are outdated, Method were moved from GraphArea to LogicCore some time ago and the logic were changed slightly to provide better performance but likely wasn't refactored completely. Now this method requires input parameters to be set. I'll update it, thanks.

**Comment by galakt** [comment]
Fixed
