### ISSUE TITLE
[Question] How to add vertex tooltip in windows form project

### ISSUE THREAD

**Issue by nugrahawahyu** [panthernet/GraphX#62]
I want to add tooltip to every vertex (windows form project), any help would be appreciated.

**Comment by panthernet** [comment]
You have to use XAML template to achieve this, specificaly add the content to the **VertexControl** **ToolTip** property. Please look here: https://github.com/panthernet/GraphX/blob/PCL/Examples/ShowcaseApp.WPF/Templates/ThemedGraphXTemplates.xaml#L97  
It adds the tooltip for vertices in **Themed Graph** showcase in **ShowcaseApp.WPF** project.

**Comment by nugrahawahyu** [comment]
Thank you very much. But how to bind vertex's data to the tooltip?

Edit - I figured it out, thank you again.
