### ISSUE TITLE
Localization not working even if language is set

### ISSUE THREAD

**Issue by alinoureldine** [panthernet/GraphX#63]
I want to change the language of the tooltips , even though the Language is set to german the tooltips are still in English . Thanks
![screenshot 13](https://cloud.githubusercontent.com/assets/12773198/18055306/999aea1a-6e07-11e6-9827-5d60392c3a6d.png)

**Comment by panthernet** [comment]
Hello, there is no localization support as there are not much string. If you want to change language in your case you should create your own **ZoomControl** style based on the default one:
https://github.com/panthernet/GraphX/blob/PCL/GraphX.Controls/Themes/Generic.xaml#L316

Please see the buttons at the link, they have **Tooltip** property set to the text you need to change.
