### ISSUE TITLE
LogicCoreChangedAction

### ISSUE THREAD

**Issue by itinerant-fox** [panthernet/GraphX#7]
Downloaded your master and tried building. The file LogicCoreChangedAction.cs in the project GraphX.WPF.Controls is missing

Had to create LogicCoreChangedAction.cs in the Enums folder with the following data

``` Csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GraphX.Controls.Enums
{
    public enum LogicCoreChangedAction
    {
        None           ,
        GenerateGraph  ,
        GenerateGraphWithEdges,
        RelayoutGraph,
        RelayoutGraphWithEdges,
    }
}
```

**Comment by panthernet** [comment]
Hi, thanks for spotting this! Missed them in the last commit :\ Fixed.

Best regards, Alexander Smirnov
Skype: panthernet

Пятница, 27 февраля 2015, 0:43 -08:00 от Kevin notifications@github.com:
