### ISSUE TITLE
Change Layout randomly

### ISSUE THREAD

**Issue by ghost** [panthernet/GraphX#71]
Hello, 
if i use e.g. the FR algorithm and then use it again by clicking a button, it changes the layout. But the algorithm is the same. So why should it change with same algorithm and same data?
Thanks:)

**Comment by ghost** [comment]
https://postimg.org/image/5ato736ql/
https://postimg.org/image/s0xedtfbx/
Same algorithm and same data but differnt layout, why?

**Comment by panthernet** [comment]
Hello, that's because some algorithms use random initial positions to provide different layout results. You can use algorithm Seed property to specify exact seed if you want one layout result to persist through many generations.

**Comment by ghost** [comment]
Can you give me an example for some algorithm please?

**Comment by panthernet** [comment]
To be correct you have to set **Seed** property for layout algorithm parameters like:
graphArea.LogicCore.DefaultLayoutAlgorithmParams.Seed = 20939202;
