### ISSUE TITLE
Edges arrows.

### ISSUE THREAD

**Issue by catrias** [panthernet/GraphX#72]
`GraphArea.ShowAllEdgesArrows(false)` doesn't work.
Custom edges that inherit from `EdgeBase` cannot be casted to `EdgeControlBase` at
`private static void showarrows_changed(object sender, DependencyPropertyChangedEventArgs args) {
            var ctrl = sender as EdgeControlBase;
`           ... }

**Comment by panthernet** [comment]
Hi, not sure what's the cause of it. If you use custom edge controls you should inherit them from **EdgeControlBase** . No way sender should be a **EdgeBase** descendant as it is the data class. If you still experience the problem it would be nice to have an example app to reproduce the issue.
