### ISSUE TITLE
Repositionning vertices automatically after "OnPropertyChanged"

### ISSUE THREAD

**Issue by SeniuuS** [panthernet/GraphX#88]
Hello,

First of all, I'd like to say your API is awesome. I can do a lot of great graph. I managed to implement Tasks that changes the property of my custom vertices and they appear on the graph with INotifyPropertyChanged.
But sometimes the modified value has a bigger height and width than before, so the vertex is bigger than before. Vertices can be one on another and it is not clean.

I would like to know if there is a method that reposition all the vertices (so I can use it at the end of my task)
Or if you have an idea.
Thank you.

**Comment by panthernet** [comment]
Sorry for not getting the responce in time. You should iterate though VertexList and call SetPosition() method for each of the verices.
