### ISSUE TITLE
[UWP] Cannot resolve Assembly System.Data.dll

### ISSUE THREAD

**Issue by michaelosthege** [panthernet/GraphX#90]
I created a blank UWP app to try out the [Tutorial](https://github.com/panthernet/GraphX/wiki/Tutorial). I referenced version 2.3.6 from NuGet, but then I get the following build error: `Cannot resolve Assembly or Windows Metadata file 'System.Data.dll'`

On a side note it would be nice to have pictures with the tutorial, or an example app in the store.

cheers

**Comment by panthernet** [comment]
Hi, I've updated the UWP part so the thing should be checked once again.
